### ISSUE TITLE
PagesのパイプラインからGithub Actionsに移行する

### ISSUE THREAD

**Issue by satler-git** [satler-git/satler-dev#16]

**Comment by satler-git** [comment]
```yaml
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1
```
